<script setup lang="ts">
import { getPercentile } from "@/utils/percentile";

const {
  sindex,
  datasetCount,
  totalCitations,
  totalMentions,
  averageFairScore,
  showRanking = true,
} = defineProps<{
  sindex: number;
  datasetCount: number;
  totalCitations: number;
  totalMentions: number;
  averageFairScore: number;
  showRanking?: boolean;
}>();

const averageDIndex = computed(() =>
  datasetCount > 0 ? sindex / datasetCount : 0,
);

const sindexPercentile = computed(() => getPercentile(sindex, "s_index"));
const datasetCountPercentile = computed(() =>
  getPercentile(datasetCount, "dataset_count"),
);
const averageFairScorePercentile = computed(() =>
  getPercentile(averageFairScore, "avg_fair_score"),
);
const averageDIndexPercentile = computed(() =>
  getPercentile(averageDIndex.value, "average_d_index"),
);
const totalCitationsPercentile = computed(() =>
  getPercentile(totalCitations, "total_citations"),
);
const totalMentionsPercentile = computed(() =>
  getPercentile(totalMentions, "total_mentions"),
);

function formatPercentile(percentile: number | null) {
  if (percentile === null) return "less than 1%";
  return `${percentile}%`;
}
</script>

<template>
  <CardCollapsibleContent title="S-Index Interpretation" class="mb-6" collapse>
    <div class="space-y-3 text-sm text-gray-700 dark:text-gray-300">
      <p>
        The <strong>S-Index</strong> (Sharing Index) is a comprehensive metric
        that represents the cumulative impact of all your datasets. It is
        calculated as the sum of Dataset Index scores across all your claimed
        datasets.
      </p>

      <p>
        <strong>What it means:</strong>
      </p>

      <ul class="ml-6 list-disc space-y-1">
        <li>
          A higher S-index indicates greater overall impact of your datasets
          relative to typical datasets in their fields of research
        </li>

        <li>
          The S-Index grows as you add more datasets or as existing datasets
          gain more citations and mentions
        </li>

        <li>
          It provides a single number to track your research data impact over
          time
        </li>
      </ul>

      <p>
        <strong>Current S-Index:</strong> {{ sindex.toFixed(1) }} (sum of
        {{ datasetCount.toLocaleString() }} dataset{{
          datasetCount !== 1 ? "s" : ""
        }}
        Dataset Index scores)
      </p>

      <template v-if="showRanking">
        <p>
          <strong>How you rank:</strong>
        </p>

        <ul class="ml-6 list-disc space-y-1">
          <li>
            Your S-index is higher than
            {{ formatPercentile(sindexPercentile) }} of researchers
          </li>

          <li>
            Your average D-Index is higher than
            {{ formatPercentile(averageDIndexPercentile) }} of researchers
          </li>

          <li>
            Your dataset count is higher than
            {{ formatPercentile(datasetCountPercentile) }} of researchers
          </li>

          <li>
            Your average FAIR score is higher than
            {{ formatPercentile(averageFairScorePercentile) }} of researchers
          </li>

          <li>
            Your total citations are higher than
            {{ formatPercentile(totalCitationsPercentile) }} of researchers
          </li>

          <li>
            Your total mentions are higher than
            {{ formatPercentile(totalMentionsPercentile) }} of researchers
          </li>
        </ul>

        <p class="text-xs text-gray-500 dark:text-gray-400">
          These rankings are calculated automatically based on our millions of
          autogenerated user S-index profiles.
        </p>
      </template>

      <p>
        More information
        <NuxtLink
          to="https://docs.scholardata.io/s-index-guide/concepts"
          target="_blank"
          rel="noopener noreferrer"
          class="text-primary hover:text-primary-600 transition-all"
          >here</NuxtLink
        >.
      </p>
    </div>
  </CardCollapsibleContent>
</template>
