name: Reindex users in Meilisearch

on:
  workflow_dispatch:

jobs:
  reindex:
    runs-on: ubuntu-latest

    env:
      KAMAL_SERVER_IP: ${{ secrets.KAMAL_SERVER_IP }}
      KAMAL_APP_NAME: ${{ secrets.KAMAL_APP_NAME }}
      KAMAL_APP_DOMAIN: ${{ secrets.KAMAL_APP_DOMAIN }}
      KAMAL_REGISTRY_LOGIN_SERVER: ${{ secrets.KAMAL_REGISTRY_LOGIN_SERVER }}
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NUXT_SESSION_PASSWORD: ${{ secrets.NUXT_SESSION_PASSWORD }}
      MEILISEARCH_API_URL: ${{ secrets.MEILISEARCH_API_URL }}
      MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NUXT_SITE_URL: ${{ secrets.NUXT_SITE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true

      - run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Boot Ofelia accessory
        run: kamal accessory boot ofelia
